# DEFAULT OPTIONS SECTION
DEFAULT_GAME_OPTIONS = 'rock,paper,scissors'
DEFAULT_GAME_OPTIONS_SEP = ','

# MENU SECTION
DEFAULT_MENU_OPTIONS = ['!rating', '!exit']

# FILES SECTION
DEFAULT_RATING_FILE_PATH = 'scripts/rating.txt'

# DEFAULT MESSAGES SECTION
DEFAULT_NAME_INPUT_MESSAGE = 'Enter your name: '
DEFAULT_GAME_GREETING_MESSAGE = 'Hello, '
DEFAULT_GAME_EXIT_MESSAGE = 'Bye!'
DEFAULT_GAME_RATING_MESSAGE = 'Your rating: '
DEFAULT_INVALID_INPUT_MESSAGE = 'Invalid input'
DEFAULT_START_GAME_MESSAGE = 'Okay, let\'s start'